const header=document.querySelector('.site-header'),menuButton=document.querySelector('.menu-button'),nav=document.querySelector('.site-nav'),navLinks=nav.querySelectorAll('a'),legalDialog=document.querySelector('#legal'),legalOpenButton=document.querySelector('[data-modal-open="legal"]'),legalCloseButton=document.querySelector('[data-modal-close]');
const setMenu=o=>{menuButton.setAttribute('aria-expanded',String(o));nav.classList.toggle('open',o);document.body.classList.toggle('menu-open',o)};
menuButton.addEventListener('click',()=>setMenu(menuButton.getAttribute('aria-expanded')!=='true'));navLinks.forEach(l=>l.addEventListener('click',()=>setMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
const updateHeader=()=>header.classList.toggle('scrolled',window.scrollY>24);updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});
legalOpenButton.addEventListener('click',()=>typeof legalDialog.showModal==='function'?legalDialog.showModal():legalDialog.setAttribute('open',''));legalCloseButton.addEventListener('click',()=>legalDialog.close());legalDialog.addEventListener('click',e=>{if(e.target===legalDialog)legalDialog.close()});

const gallery=document.querySelector('.gallery');
if(gallery){
 const stage=gallery.querySelector('.gallery-stage'),dotsWrap=gallery.querySelector('.gallery-dots'),count=gallery.querySelector('.gallery-count');
 const items=[
 ['assets/gallery/2026-championship-celebration-bar.jpg','The Boathouse Beers team celebrating together at the bar after winning the 2026 championship','Championship celebration'],
 ['assets/gallery/fall-2025-team-photo.jpg','The Boathouse Beers Fall 2025 team posing together in matching jerseys','Fall 2025 team'],
 ['assets/gallery/2025-season-banquet-cavalier.jpg','Boathouse Beers teammates together after dinner at The Cavalier in San Francisco for the 2025 season banquet','2025 season banquet · The Cavalier, San Francisco'],
 ['assets/gallery/2025-summer-banquet.svg','Boathouse Beers teammates and friends gathered outdoors at night during the 2025 summer banquet','Summer 2025 banquet'],
 ['assets/gallery/2024-banquet-topgolf.jpg','Boathouse Beers teammates and friends together at Topgolf for the 2024 team banquet','2024 banquet · Topgolf'],
 ['assets/gallery/2023-first-season-banquet.svg','Boathouse Beers teammates together at the 2023 banquet after the team\'s first season','2023 banquet · After our first season'],
 ['assets/gallery/first-win-team-fixed.jpg.b64','The Boathouse Beers team posing together on the softball field after their first win','After our first win']];
 items.forEach(([src,alt,caption],i)=>{const slide=document.createElement('figure');slide.className='gallery-slide';slide.dataset.slide='';slide.setAttribute('aria-hidden','true');const img=document.createElement('img');img.alt=alt;img.loading='lazy';if(src.endsWith('.b64')){fetch(src,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.text()}).then(b=>img.src='data:image/jpeg;base64,'+b.trim()).catch(()=>{img.style.display='none';slide.classList.add('image-missing')})}else img.src=src;img.addEventListener('error',()=>{img.style.display='none';slide.classList.add('image-missing')});const fc=document.createElement('figcaption');fc.textContent=caption;slide.append(img,fc);stage.appendChild(slide);const dot=document.createElement('button');dot.type='button';dot.dataset.galleryDot=String(i+2);dot.setAttribute('aria-label',`Show photo ${i+3}`);dotsWrap.appendChild(dot)});
 const slides=[...gallery.querySelectorAll('[data-slide]')],dots=[...gallery.querySelectorAll('[data-gallery-dot]')],prev=gallery.querySelector('[data-gallery-prev]'),next=gallery.querySelector('[data-gallery-next]'),reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(count)count.innerHTML=`<span data-gallery-current>1</span> / ${slides.length}`;const current=gallery.querySelector('[data-gallery-current]');let active=0,timer,touchX=0;
 const show=i=>{active=(i+slides.length)%slides.length;slides.forEach((s,n)=>{const on=n===active;s.classList.toggle('is-active',on);s.setAttribute('aria-hidden',String(!on))});dots.forEach((d,n)=>{const on=n===active;d.classList.toggle('is-active',on);on?d.setAttribute('aria-current','true'):d.removeAttribute('aria-current')});if(current)current.textContent=String(active+1)};
 const stop=()=>clearInterval(timer),start=()=>{if(!reduced){stop();timer=setInterval(()=>show(active+1),6000)}};prev.addEventListener('click',()=>{show(active-1);start()});next.addEventListener('click',()=>{show(active+1);start()});dots.forEach(d=>d.addEventListener('click',()=>{show(Number(d.dataset.galleryDot));start()}));gallery.addEventListener('mouseenter',stop);gallery.addEventListener('mouseleave',start);gallery.addEventListener('focusin',stop);gallery.addEventListener('focusout',start);gallery.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')show(active-1);if(e.key==='ArrowRight')show(active+1)});gallery.addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});gallery.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>45)show(active+(d<0?1:-1))},{passive:true});start();
}

const addBanquetPhoto=(matcher,src,alt)=>{const card=[...document.querySelectorAll('.banquet-card')].find(matcher);if(card&&!card.querySelector('img')){const p=document.createElement('img');p.src=src;p.alt=alt;p.loading='lazy';Object.assign(p.style,{width:'100%',aspectRatio:'4 / 3',objectFit:'cover',borderRadius:'14px',marginBottom:'1rem'});card.prepend(p)}};
addBanquetPhoto(c=>c.classList.contains('banquet-latest'),'assets/gallery/2025-season-banquet-cavalier.jpg','Boathouse Beers teammates together after dinner at The Cavalier in San Francisco for the 2025 season banquet');
addBanquetPhoto(c=>c.querySelector('h3')?.textContent.includes('Coach’s backyard'),'assets/gallery/2025-summer-banquet.svg','Boathouse Beers teammates and friends gathered outdoors at night during the Summer 2025 banquet in the coach\'s backyard');
addBanquetPhoto(c=>c.querySelector('h3')?.textContent.includes('Topgolf'),'assets/gallery/2024-banquet-topgolf.jpg','Boathouse Beers teammates and friends together at Topgolf for the 2024 team banquet');
addBanquetPhoto(c=>c.querySelector('h3')?.textContent.includes('Boathouse Tavern'),'assets/gallery/2023-first-season-banquet.svg','Boathouse Beers teammates together at the 2023 banquet after the team\'s first season');

const sponsorSection=document.querySelector('#sponsor');if(sponsorSection){const sponsorCopy=sponsorSection.querySelector('.sponsor-copy'),sponsorBadge=sponsorSection.querySelector('.sponsor-badge');if(sponsorCopy&&!sponsorCopy.querySelector('.sponsor-location')){const b=document.createElement('div');b.className='sponsor-location';b.innerHTML='<p style="margin:1.5rem 0 .35rem;font-weight:800;color:#fff;">2030 Clement Avenue</p><p style="margin:0 0 .75rem;">Alameda, CA 94501</p><a href="https://www.google.com/maps/search/?api=1&query=2030+Clement+Avenue+Alameda+CA+94501" target="_blank" rel="noopener" style="display:inline-block;margin-bottom:1.25rem;color:#f7b928;font-weight:800;text-decoration:none;">Open in Google Maps ↗</a><div style="overflow:hidden;border-radius:16px;border:1px solid rgba(255,255,255,.18);width:100%;max-width:620px;box-shadow:0 18px 45px rgba(0,0,0,.22);"><iframe title="Boathouse Tavern map" src="https://www.google.com/maps?q=2030+Clement+Avenue,+Alameda,+CA+94501&output=embed" width="100%" height="280" style="border:0;display:block;" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>';const v=sponsorCopy.querySelector('.button');v?sponsorCopy.insertBefore(b,v):sponsorCopy.appendChild(b)}if(sponsorBadge)sponsorBadge.innerHTML='<a href="https://www.boathousealameda.net/" target="_blank" rel="noopener" style="display:flex;width:100%;height:100%;min-height:360px;align-items:center;justify-content:center;padding:2rem;text-decoration:none;background:#fff;"><img src="https://images.squarespace-cdn.com/content/v1/61c2640cf8c3e52283ca6e7a/1641356661785-5VEK3UL667TF28IYMHSL/IMG_3288.jpg" alt="Boathouse Alameda logo" style="display:block;max-width:100%;max-height:330px;width:auto;height:auto;margin:0 auto;object-fit:contain;" loading="lazy" /></a>'}

const heroSection=document.querySelector('.hero');
if(heroSection&&!document.querySelector('[data-tonights-lineup]')){
 const section=document.createElement('section');
 section.dataset.tonightsLineup='';
 section.setAttribute('aria-label','Week 2 line-up');
 Object.assign(section.style,{background:'#071426',padding:'clamp(28px,5vw,64px) 20px',textAlign:'center',borderTop:'1px solid rgba(255,255,255,.08)',borderBottom:'1px solid rgba(255,255,255,.08)'});
 section.innerHTML='<div style="max-width:780px;margin:0 auto;"><p style="margin:0 0 8px;color:#e3262e;font-family:\'Barlow Condensed\',sans-serif;font-size:1rem;font-weight:800;letter-spacing:.16em;text-transform:uppercase;">Game Day · August 25</p><h2 style="margin:0 0 8px;color:#fff;font-family:\'Barlow Condensed\',sans-serif;font-size:clamp(2.2rem,7vw,4.25rem);line-height:.95;text-transform:uppercase;">Week 2 Line-up</h2><p style="margin:0 0 24px;color:#c7d0db;font-size:1rem;">Boathouse Beers vs. Misfits · 7:00 PM</p><img src="assets/lineup-2026-08-25.svg?v=20260827-2" alt="Boathouse Beers Week 2 line-up for the August 25 game against the Misfits at 7:00 PM" style="display:block;width:min(100%,560px);height:auto;margin:0 auto;border-radius:16px;box-shadow:0 22px 55px rgba(0,0,0,.38);" /></div>';
 heroSection.insertAdjacentElement('afterend',section);
}

document.querySelector('#year').textContent=new Date().getFullYear();